apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    last: final
    author: "Ismoil"
  name: nginx1
  namespace: ismoil
spec:
  containers:
  - image: nginx
    name: nginx1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
