apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: echo-pod
  name: echo-pod
  namespace: ismoil
spec:
  containers:
  - args:
    - echo
    - The Best DevOps Course!
    image: busybox
    name: echo-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
