apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: ismoil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: AUTHOR
          valueFrom:
            configMapKeyRef:
              name: config-info
              key: AUTHOR
        - name: EXAM_TYPE
          valueFrom:
            configMapKeyRef:
              name: config-info
              key: EXAM_TYPE
        - name: Message              
        command: ["/bin/echo"]
        args: ["-c", "My name is $(AUTHOR) and this is my $(EXAM_TYPE); sleep 5000;done"]    
        ports:
        - containerPort: 80
        resources: {}
status: {}
